steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
   - 'build'
    - '--tag=gcr.io/$PROJECT_ID/android:base-ndk-r17b'
    - '--build-arg'
    - 'android_version=base'
    - '--build-arg'
    - 'project_id=$PROJECT_ID'
    - '--file=Dockerfile-ndk'
    - '.'
    - '--cache-from'
    - 'gcr.io/$PROJECT_ID/android:base'

  images:
    - 'gcr.io/$PROJECT_ID/android:base-ndk-r17b'